FIND_PATH(SDL2_MIXER_INCLUDE_DIR SDL_mixer.h HINTS $ENV{SDL2MIXER}/i686-w64-mingw32 PATH_SUFFIXES include/SDL2)

FIND_LIBRARY(SDL2_MIXER_LIBRARY SDL2_mixer HINTS $ENV{SDL2MIXER}/i686-w64-mingw32 PATH_SUFFIXES lib)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_MIXER REQUIRED_VARS SDL2_MIXER_LIBRARY SDL2_MIXER_INCLUDE_DIR)
