# Locate BOX2D library

FIND_PATH(
	BOX2D_INCLUDE_DIR 
	Box2D/Box2D.h
	HINTS
		$ENV{BOX2D}
	PATH_SUFFIXES
		Box2D
)

FIND_LIBRARY(
	BOX2D_LIBRARY_TEMP
	Box2D
	HINTS
		$ENV{BOX2D}
	PATH_SUFFIXES 
		Box2D/Build/vs2013/bin/x32/Debug
)

SET(BOX2D_FOUND "NO")

IF(BOX2D_LIBRARY_TEMP)
	
	# Set the final string here so the GUI reflects the final state.
	SET(BOX2D_LIBRARY ${BOX2D_LIBRARY_TEMP} CACHE STRING "Where the BOX2D Library can be found")

	# Set the temp variable to INTERNAL so it is not seen in the CMake GUI
	SET(BOX2D_LIBRARY_TEMP "${BOX2D_LIBRARY_TEMP}" CACHE INTERNAL "")

	SET(BOX2D_FOUND "YES")
ENDIF(BOX2D_LIBRARY_TEMP)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(BOX2D REQUIRED_VARS BOX2D_LIBRARY BOX2D_INCLUDE_DIR)

