FIND_PATH(SDL2_INCLUDE_DIR SDL.h HINTS $ENV{SDL2}/i686-w64-mingw32 PATH_SUFFIXES include/SDL2)

FIND_LIBRARY(SDL2_LIBRARY SDL2 HINTS $ENV{SDL2}/i686-w64-mingw32 PATH_SUFFIXES lib)

FIND_LIBRARY(SDL2MAIN_LIBRARY SDL2main HINTS $ENV{SDL2}/i686-w64-mingw32 PATH_SUFFIXES lib)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2 REQUIRED_VARS SDL2_LIBRARY SDL2_INCLUDE_DIR)

