FIND_PATH(SDL2_IMAGE_INCLUDE_DIR SDL_image.h HINTS $ENV{SDL2IMAGE}/i686-w64-mingw32 PATH_SUFFIXES include/SDL2)

FIND_LIBRARY(SDL2_IMAGE_LIBRARY SDL2_image HINTS $ENV{SDL2IMAGE}/i686-w64-mingw32 PATH_SUFFIXES lib)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_IMAGE REQUIRED_VARS SDL2_IMAGE_LIBRARY SDL2_IMAGE_INCLUDE_DIR)
